### ISSUE TITLE
fatal error: 'sys/inotify.h' file not found

### ISSUE THREAD

**Issue by Megidd** [idea4bsd/fsnotifier#2]
On FreeBSD 10.3-STABLE I run these:

`git clone https://github.com/idea4bsd/fsnotifier`
`cd fsnotifier/`
`make`

Then I receive the following error:

`inotify.c:25:10: fatal error: 'sys/inotify.h' file not found`
`#include <sys/inotify.h>`
`         ^`
`1 error generated.`
`*** Error code 1`

`Stop.`

**Comment by t6** [comment]
Install libinotify: https://www.freshports.org/devel/libinotify/

Or use the fsnotifier port: https://www.freshports.org/java/intellij-fsnotifier

**Comment by Megidd** [comment]
Thanks, I ran 

`sudo pkg install libinotify`

and the error got resolved
